# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    #build and deploy angular application to 'Github pages'
    build-and-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout code
              uses: actions/checkout@v2

            #Setup node.js
            - name: Setup Node.js environment
              uses:
                  actions/setup-node@v2.1.5

            #Cache npm dependency
            - name: Cache node.js modules
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.OS }}-npm-cache-

            #Build Angular Application
            - name: Build Angular Application
              run: |
                npm install
                npm run build -- --prod --base-href="./"
                pwd
            #Publish to github pages
            - name: Publish
              env:
                API_TOKEN : ${{secrets.DEPLOY_TO_FUNDLINE_MASTER}}
              run : |
                echo "~~~~~~~~~~~~Make directory~~~~~~~~~~~~"
                mkdir ../Publish
                cd ../Publish
                echo "~~~~~~~~~~~~git clone~~~~~~~~~~~~"
                git clone https://github.com/FUNDLINE/FUNDLINE.github.io.git
                cd FUNDLINE.github.io
                echo "~~~~~~~~~~~~copy~~~~~~~~~~~~"
                rm -f *
                rm -rf *
                cp -v -r -f ../../FUNDLINE-website/dist/FUNDLINE-website/* .
                echo "~~~~~~~~~~~~commit and push~~~~~~~~~~~~"
                git config --local user.name "G-Basak"
                git config --local user.email "basak.gunjan@gmail.com"
                if [ $(git status --porcelain | wc -l) -eq "0" ]; then
                    exit 0
                else
                    git add --verbose --ignore-errors --all
                    git commit --verbose -m "Automated Deploy"
                    git push https://G-Basak:$API_TOKEN@github.com/FUNDLINE/FUNDLINE.github.io.git refs/heads/master
                fi