# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    #build and deploy angular application to 'Github pages'
    build-and-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses:
                  actions/setup-node@v2.1.5
                  # Install Angulat CLI
            - name: Install Angular CLI
              run: sudo npm install -g @angular/cli

            # Build Angular Application
            - name: Build Angular Application
              run: $GITHUB_WORKSPACE/.github/workflows/BuildAngularApp.sh

            #Deploy application to 'Github Pages'
            - name: Deploy application
              env:
                  API_TOKEN: ${{ secrets.DEPLOY_TO_FUNDLINE_MASTER}}
              run: $GITHUB_WORKSPACE/.github/workflows/DeployApp.sh